# Uncomment this line to define a global platform for your project
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '7.0'

target 'PPTMapView' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  #pod 'Alamofire', '>= 3.4.0'    #, :git => 'https://github.com/Alamofire/Alamofire.git', :branch => 'swift3'
  #pod 'OAuthSwift'             #, :git => 'https://github.com/OAuthSwift/OAuthSwift.git', :branch => 'swift3.0'

  #pod 'Alamofire', :git => 'https://github.com/Alamofire/Alamofire.git', :branch => 'swift3'

  # Pods for PPTMapView

  #pod 'react-native-maps', :path => '../node_modules/react-native-maps'

  pod 'GoogleMaps'
  #pod 'GooglePlaces'

  #target 'PPTMapViewTests' do
  #  inherit! :search_paths
  #  # Pods for testing
  #end

	post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES'] = 'NO'
        end
    end
	end

end

